spring.application.name=database_migration

spring.datasource.url=jdbc:mysql://localhost:3306/databas_migration_learn
spring.datasource.username=root
spring.datasource.password=supersecretpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver